// This file is for layer in neural network, which will be used in network and which uses neurons from neuron.go
// Idea for the struct Layer and method Forward is generated by ChatGPT. Further functions are my own doing.
// I have also commented everything manually to understand the code and to make it understandable
package network

// Defining struct layer. Layer only consists of neurons, and has no
// other fields or information to it
type Layer struct {
	Neurons []Neuron
}

// Defining function Forward. This function gets layer method receiver that it
// uses to access other layers in the neural network. It takes inputs as
// parameter and returns list of outputs, one float64 for each output connection
func (l *Layer) Forward(inputs []float64) []float64 {
	// Make a slice of output that consists of lists of outputs for each neuron
	outputs := make([]float64, len(l.Neurons))
	// Loops over each neuron in l.Neurons, adds result of activation to
	// each neurons output.
	for i, neuron := range l.Neurons {
		outputs[i] = neuron.Activate(inputs)
	}
	return outputs
}

// Function for counting neurons in given layer
func (l *Layer) length() int {
	return len(l.Neurons)
}
