// This file will be used for network, which will consist of layers.
// Struct NeuralNetwork and function Predict are generated by ChatGPT. Further functions are my own doing.
// I have also commented everything manually to understand the code and to make it understandable
package network

import "fmt"

// NeuralNetwork consists of layers of neurons. It has no adjustable parameters other than layers.
type NeuralNetwork struct {
	Layers []Layer
}

// Creating a function for single forward pass.
// nn pointer to neural network that can read and modify layers
// Takes input slice as parameter, and returns output slice that is the output of network.
func (nn *NeuralNetwork) Predict(input []float64) []float64 {
	// Creating a slice output, that will keep the output values of last processed layer. Starting
	// with input, as it is what comes before first layer.
	output := input

	// Loop through all the layers in the neural network updating outputs as we move through layers
	for _, layer := range nn.Layers {
		output = layer.Forward(output)
	}
	return output
}

// Function for printing structure of neural network for debugging and checking that everything works.
// Will be refined later to be more informative and visually nicer :)
func (nn *NeuralNetwork) PrintLayers() {
	fmt.Print("Amount of neurons in each layer in the neural network: \n")
	for layer := range nn.Layers {
		fmt.Print("layer ", layer, ": ", nn.Layers[layer].Length(), "\n")
	}
}

// Constructor for neural network
func NewNeuralNetwork(layers []Layer) *NeuralNetwork {
	temp := &NeuralNetwork{
		Layers: layers,
	}
	return temp
}
